### ISSUE TITLE
Minimal Example

### ISSUE THREAD

**Issue by expeditioneer** [ribbons/android-rsync#4]
Thank you for your work!

This is not really a bug but i don't know where else to report this.

Is it possible that you provide a minimal code example for using your library?

**Comment by ribbons** [comment]
No worries, I think this can be classed as a documentation bug so it is the right place :smile:

I'm just in the process of putting together an Android app which uses this binary (as well as the dropbear binaries from [my other repo](https://github.com/ribbons/android-dropbear)) - my plan is to add a link to that in the README once I've pushed that to GitHub as well.  I'll update this issue when I've done that so you can let me know if that makes it clear or I need to add some more info :+1:

**Comment by expeditioneer** [comment]
@ribbons thank you for your fast reply :-)

Is there an ETA? If this would need 'a lot' longer. I would be really happy with a short gist.

**Comment by ribbons** [comment]
It'll be a little while, keep getting diverted by other projects and I'm a bit slow with Android development as I don't do that much but to point you in the right kind of direction here is some rough Kotlin for running the packaged binary:
``` kotlin
        Log.d(TAG, "About to run rsync")
        val libDir = context.applicationInfo.nativeLibraryDir

        val args = ArrayList<String?>()
        args.add("$libDir/librsync.so")
        args.add("--version")

        val rsync = Runtime.getRuntime().exec(args.toTypedArray())
        val result = rsync.waitFor()

        val output = RsyncOutput(
            rsync.inputStream.bufferedReader().use(BufferedReader::readText),
            rsync.errorStream.bufferedReader().use(BufferedReader::readText),
        )

        Log.d(TAG, "Run completed, exit code $result")
```
