### ISSUE TITLE
Maven repository does not allow anonymous access

### ISSUE THREAD

**Issue by vitalyster** [ribbons/android-rsync#42]
Could not GET 'https://maven.pkg.github.com/ribbons/android-rsync/com/nerdoftheherd/android-rsync/3.2.7/android-rsync-3.2.7.pom'. Received status code 401 from server: Unauthorized

**Comment by ribbons** [comment]
It's public (e.g. any authenticated user can access it) but unfortunately doesn't allow anonymous access which is a pain but unfortunately still appears to be a limitation on the GitHub end (last time I checked, only their Docker package registry supported anonymous access).  There were positive murmurings from GitHub a couple of years ago that anonymous access would be enabled 'soon' but unfortunately hasn't happened yet :roll_eyes:.

You can check out my workaround for this annoyance in [one of my other repositories](https://github.com/ribbons/TaskerRsync/blob/master/build.gradle.kts) combined with setting gpr.user and gpr.key in my local `~/.gradle/gradle.properties`

**Comment by vitalyster** [comment]
Maybe you can publish to Maven Central?

**Comment by ribbons** [comment]
> Maybe you can publish to Maven Central?

I'm not massively opposed to the idea but not hugely motivated (as what's published in the GitHub package registry works for me) so would be open to a PR to add this to the Actions workflow if someone else is happy to put in the leg-work of figuring out the process.
