### ISSUE TITLE
Tried to connect with SSH but it's not working.

### ISSUE THREAD

**Issue by begouravdev** [ribbons/android-rsync#57]
# Logs
Exit code: 12
Output: rsync: [sender] Failed to exec /data/data/com.app/.ssh/id_rsa: Permission denied (13)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.3.0]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.3.0]

# Here are my Public/Private keys:
<img width="343" alt="Screenshot 2024-04-22 at 4 19 16 PM" src="https://github.com/ribbons/android-rsync/assets/97372439/58874045-2fcc-42f6-8fca-c1439fee76c7">

# My Code Block
```Java
try {
            String libDir = getReactApplicationContext().getApplicationInfo().nativeLibraryDir;
            ProcessBuilder builder;
            Process process;

            List<String> args = new ArrayList<>();
            args.add(libDir + "/librsync.so");
            // args.add("-e");
            // args.add("/data/data/com.app/.ssh/id_rsa"); // Tried with Custom path to SSH binary as well
            args.add("-avz");
            args.add("/storage/emulated/0/Pictures/Screenshots/Screenshot_2024-04-10-17-26-43-21_84d3000e3f4017145260f7618db1d683.jpg");
            args.add("awesomedev@192.168.1.6:/Users/awesomedev/rsync/"); // Tried with this path as well: ~/rsync/ then error code is 14
            builder = new ProcessBuilder(args);
            builder.redirectErrorStream(true);
            process = builder.start();

            BufferedReader inputReader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            BufferedReader errorReader = new BufferedReader(new InputStreamReader(process.getErrorStream()));
            StringBuilder output = new StringBuilder();
            StringBuilder errorOutput = new StringBuilder();
            String line;

            while ((line = inputReader.readLine()) != null) {
                output.append(line + "\n");
            }
            while ((line = errorReader.readLine()) != null) {
                errorOutput.append(line + "\n");
            }

            int exitCode = process.waitFor();
            inputReader.close();
            errorReader.close();

            Log.d("RsyncModule", "Exit code: " + process.exitValue());
            callback.invoke("Data transferred.  " + "Exit code: " + exitCode + " Output: " + output.toString() + " Errors: " + errorOutput.toString());

        } catch (IOException | InterruptedException e) {
            Log.e("RsyncModule ", "Error executing command", e);
            callback.invoke("Error executing command: " + e.getMessage());
        }
```

# With the use of Termux or Mac everything works fine.
![Screenshot_2024-04-22-12-34-07-17_84d3000e3f4017145260f7618db1d683](https://github.com/ribbons/android-rsync/assets/97372439/af27cc68-0059-435c-a687-3bc6a7a30c6c)

# My Manifest permissions
<img width="674" alt="Screenshot 2024-04-22 at 4 26 35 PM" src="https://github.com/ribbons/android-rsync/assets/97372439/0c9e0d13-372d-41e3-b7bb-1a85ea498715">

# With the use of the same Public/Private key I'm able to connect using Jsch.
![Screenshot 2024-04-21 at 12 07 26 PM](https://github.com/ribbons/android-rsync/assets/97372439/553d75dd-74f1-46da-8d93-d20bb0cc7914)

**Comment by ribbons** [comment]
> Output: rsync: [sender] Failed to exec /data/data/com.app/.ssh/id_rsa: Permission denied (13)
> rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.3.0]
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.3.0]

The supplied code doesn't seem to quite match but I'm guessing the log was produced with those two lines uncommented.  The rsync `-e` switch [specifies the remote shell binary to run](https://download.samba.org/pub/rsync/rsync.1#opt-e), so you're asking rsync to execute your private key file `/data/data/com.app/.ssh/id_rsa` which (unsurprisingly) isn't set as executable, hence that error.

It sounds like it would be worth your while checking out how my [Rsync for Tasker](https://github.com/ribbons/TaskerRsync) app does things as a full example (or even use the relevant parts of the code directly as long as you comply with the terms of version 3 of the GPL).

Is there anything specific you wanted to report as an issue with this build of rsync?

**Comment by begouravdev** [comment]
> > Output: rsync: [sender] Failed to exec /data/data/com.app/.ssh/id_rsa: Permission denied (13)
> > rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.3.0]
> > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> > rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.3.0]
> 
> The supplied code doesn't seem to quite match but I'm guessing the log was produced with those two lines uncommented. The rsync `-e` switch [specifies the remote shell binary to run](https://download.samba.org/pub/rsync/rsync.1#opt-e), so you're asking rsync to execute your private key file `/data/data/com.app/.ssh/id_rsa` which (unsurprisingly) isn't set as executable, hence that error.
> 
> It sounds like it would be worth your while checking out how my [Rsync for Tasker](https://github.com/ribbons/TaskerRsync) app does things as a full example (or even use the relevant parts of the code directly as long as you comply with the terms of version 3 of the GPL).
> 
> Is there anything specific you wanted to report as an issue with this build of rsync?

Hi @ribbons I already go through **Rsync Tasker Android** project. But I used Jsch for private/public key generation. So my question is:
1. If this path `/data/data/com.app/.ssh/id_rsa` is not what rsync looking for, what is the default path?
2. I believe I can set it manually So can I set a manual path without using `ssh i` or dropbear?

Regarding point 1 I'm very curious because on Termux I didn't define any ssh path by default it's picking from here: `/data/data/{termux-package-name}/.ssh/id_rsa`.

**Comment by begouravdev** [comment]
Btw this is an open-source project. You can check `dev` branch. 
Here is the [link](https://gitlab.com/whitebox-aero/mobile-sync/-/tree/dev?ref_type=heads).

**Comment by begouravdev** [comment]
Hi @ribbons did you get a chance to check above request 🙂

**Comment by ribbons** [comment]
> Hi @ribbons did you get a chance to check above request 🙂

Not until this evening, no - I was working late yesterday.

> Hi @ribbons I already go through Rsync Tasker Android project. But I used Jsch for private/public key generation. So my question is:
> [...]

My apologies but I don't have the availability to provide integration support to everyone using these builds of rsync.  I'm (of course) happy to receive reports of issues directly related to how the binaries are being built (expected rsync features being omitted from the builds, bad build configuration etc).  Sorry to be somewhat of a stuck record but the source of Rsync for Tasker does contain all the clues you need in this case 🙂.

I'm going to go ahead and close this issue, feel free to reopen it if I've misunderstood and there is a specific issue with how the code in this repo is building rsync.
