### ISSUE TITLE
Feature - Add rrsync

### ISSUE THREAD

**Issue by yhojann-cl** [ribbons/android-rsync#59]
Please, add the `rrsync` binary for serve rsync with a ssh server like as `net.xnano.android.sshserver`.

**Comment by ribbons** [comment]
Perhaps I'm misunderstanding, but [rrsync is a python script](https://github.com/RsyncProject/rsync/blob/master/support/rrsync) so it isn't something that can be compiled like the rsync binary itself.

Would you be able to clarify your request?

**Comment by ribbons** [comment]
Closing as no response received.
